---

- name: create /etc/prometheus
  file:
    path: /etc/prometheus
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create the prometheus user
  group:
    name: prometheus
    state: present

- name: create the prometheus user
  user:
    name: prometheus
    group: prometheus
    shell: /bin/false
    create_home: false
    state: present

- name: create /var/lib/prometheus
  file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755

- name: fetch latest node_exporter version
  shell: curl -s -o /dev/null -I -w "%{redirect_url}\n" https://github.com/prometheus/node_exporter/releases/latest | grep -oP "[0-9]+(\.[0-9]+)+$"
  args:
    executable: /bin/bash
  register: node_exporter_version

- name: download node_exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version.stdout }}/node_exporter-{{ node_exporter_version.stdout }}.linux-amd64.tar.gz
    owner: root
    group: root
    dest: /root/node_exporter-{{ node_exporter_version.stdout }}.linux-amd64.tar.gz
    mode: 0755

- name: Unarchive node_exporter
  unarchive:
    src: /root/node_exporter-{{ node_exporter_version.stdout }}.linux-amd64.tar.gz
    dest: /root
    remote_src: yes

- name: copy node_exporter to /usr/local/bin/node_exporter
  copy:
    src: /root/node_exporter-{{ node_exporter_version.stdout }}.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    owner: prometheus
    group: prometheus
    mode: 0755
    remote_src: yes

- name: add node_exporter systemd unit file
  template:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    mode: 0644

- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: enable node_exporter
  systemd:
    name: node_exporter
    enabled: yes

- name: start node_exporter
  systemd:
    name: node_exporter
    state: started

- name: set kernel.perf_event_paranoid
  lineinfile:
    path: /etc/sysctl.conf
    regexp: "^kernel.perf_event_paranoid"
    line: "kernel.perf_event_paranoid={{ prometheus_node_exporter_sysctl_perf }}"
    state: present

- name: apply kernel.perf_event_paranoid
  command: sysctl -p

...
